---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses: {{ .Values.addresses | toJson }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
spec:
  ipAddressPools:
    - default
